baseURL = 'https://fkea1da.github.io/about-fkea1da.github.io/'
languageCode = 'ru-ru'
title = 'Портфолио'
theme = "PaperMod"
disableKinds = ["RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true